Fix type in Range attribute: change from double to int
An exception was thrown while loading the test.
System.InvalidOperationException: A value of type System.Int32 (1) cannot be passed to a parameter of type System.Double.